[package]
name = "egui-directx11"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
egui = "0.26.2"
windows = { version = "0.54.0", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
] }

[workspace]
resolver = "2"
members = ["examples/*"]
