[package]
name = "egui-directx11"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4.21"
egui = "0.26.2"
windows = { version = "0.54.0", features = [
    "Win32_Foundation",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
]}

[dev-dependencies]
egui_demo_lib = "0.26.2"
egui-winit = { version = "0.26.2", default-features = false }
pretty_env_logger = "0.5.0"
winit = { version = "0.29.10", default-features = false, features = ["rwh_06"] }
